---
title: "Final presentation"
author: "Kayla Esser"
format: revealjs
editor: visual
---

## Introduction

The purpose of this function is to identify and create a vector of all records in a longitudinal data set wherein there has been a specific change in a specified variable over a certain time interval

## Applications

This function suits many purposes within longitudinal data processing and analysis. For example, imagine you are researching longitudinal trends in depression, and would like to count how many patients had a positive change in PHQ-9 score between their one-year follow up and baseline? Or say you are measuring spending over time, and would like to see the proportion of participants that spent less money at year 5 compared to year 1. Maybe you are interested in seeing whether the size of a tumour has grown, shrunk, or stayed the same across follow up appointments.

The longdiff function allows you to specify the time interval of interest and magnitude and direction of change in a certain variable, and create a subset of your study population using this information.

## Objectives and goals

## Code overview

## Examples

## Questions?
